version: '3.8'
services:
  billing-proxy:
    container_name: billing-proxy-container
    build:
      dockerfile: Dockerfile
    image: dome/billing-proxy:latest
    restart: always
    ports:
      - 8000:8080